### PR TITLE
Fix for VSCode 1.31

### LINKED ISSUE #1: Does not work on VS Code 1.23.1
I followed the steps - installed the extension and added to user settings:

    "vscode_custom_css.imports": [
        "file:///Users/iamdev/.vscode/extensions/pzuraq.vertical-tab-bar-1.0.0/styles.css"
    ]

It does change nothing and says "Unknown configuration setting". The file path is correct, cmd+click opening

(using macOS)

### PR DESCRIPTION
**Pull request by JavierCane**
Fixes https://github.com/pzuraq/vscode-vertical-tab-bar/issues/1

Result:

vscode_settings json dotfiles unsupported 2019-02-25 12-00-12

### CODE REVIEW

**Review by Ruffo324 — APPROVED** [review]
Nice! Finally a working version (Y)

If i have the time i would optimize this, to support tab-moving.

**Comment by akeeton** [comment]
This fix doesn't work for version 1.34.20-insider

**Comment by calvinjc** [comment]
This worked in 1.34 but no longer works in 1.35.  Has anyone updated the css to work with 1.35 yet?

**Comment by calvinjc** [comment]
I created a new PR (#3) to update this to work in 1.36

**Pull request closed without merging**
